# Dependencies
markdown:         rdiscount
highlighter:      pygments

# Permalinks
# permalink:        pretty

# Setup
title:            Documentation
tagline:          'for the Maniaplanet game operating system'
description:      '<div style="text-align:center;"><a href="/"><img src="/img/maniaplanet.png"/></a></div>'
url:              http://www.maniaplanet.com
baseurl:          '/'
paginate:         5
docurl:           http://doc.maniaplanet.com

author:
  name:           'Nadeo'
  url:            https://twitter.com/Maniaplanet

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/maniaplanet/documentation

gems:
  - jekyll-sitemap

rdiscount:
    extensions:
      - autolink
      - generate_toc
